export enum AttributionModelType {
  LAST_CLICK = 'LAST_CLICK',
  FIRST_CLICK = 'FIRST_CLICK',
  LINEAR = 'LINEAR',
  TIME_DECAY = 'TIME_DECAY',
  U_SHAPED = 'U_SHAPED',
  DATA_DRIVEN = 'DATA_DRIVEN',
}
