export enum PriceExtensionType {
  UNKNOWN = 'UNKNOWN',
  BRANDS = 'BRANDS',
  EVENTS = 'EVENTS',
  LOCATIONS = 'LOCATIONS',
  NEIGHBORHOODS = 'NEIGHBORHOODS',
  PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES',
  PRODUCT_TIERS = 'PRODUCT_TIERS',
  SERVICES = 'SERVICES',
  SERVICE_CATEGORIES = 'SERVICE_CATEGORIES',
  SERVICE_TIERS = 'SERVICE_TIERS',
}
