export enum TrialStatus {
  UNKNOWN = 'UNKNOWN',
  CREATING = 'CREATING',
  ACTIVE = 'ACTIVE',
  PROMOTING = 'PROMOTING',
  PROMOTED = 'PROMOTED',
  ARCHIVED = 'ARCHIVED',
  CREATION_FAILED = 'CREATION_FAILED',
  PROMOTE_FAILED = 'PROMOTE_FAILED',
  GRADUATED = 'GRADUATED',
  HALTED = 'HALTED',
}
