export enum PolicyTopicEvidenceType {
  UNKNOWN = 'UNKNOWN',
  AD_TEXT = 'AD_TEXT',
  HTTP_CODE = 'HTTP_CODE',
  WEBSITES = 'WEBSITES',
  LANGUAGE = 'LANGUAGE',
  AD_TEXT_LIST = 'AD_TEXT_LIST',
  DESTINATION_TEXT_LIST = 'DESTINATION_TEXT_LIST',
  DESTINATION_MISMATCH = 'DESTINATION_MISMATCH',
}
