export enum PolicyApprovalStatus {
  UNKNOWN = 'UNKNOWN',
  APPROVED = 'APPROVED',
  APPROVED_LIMITED = 'APPROVED_LIMITED',
  ELIGIBLE = 'ELIGIBLE',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DISAPPROVED = 'DISAPPROVED',
  SITE_SUSPENDED = 'SITE_SUSPENDED',
}
