export enum PolicyTopicEvidenceDestinationMismatchUrlType {
  UNKNOWN = 'UNKNOWN',
  DISPLAY_URL = 'DISPLAY_URL',
  FINAL_URL = 'FINAL_URL',
  FINAL_MOBILE_URL = 'FINAL_MOBILE_URL',
  TRACKING_URL = 'TRACKING_URL',
  MOBILE_TRACKING_URL = 'MOBILE_TRACKING_URL',
}
